### PR TITLE
Add eslint and prettier and format on commit with husky

### LINKED ISSUE #7: Add eslint and prettier to client and server

### LINKED ISSUE #19: Add Pre-commit Hooks using Husky

### PR DESCRIPTION
**Pull request by NLmeng**

### CODE REVIEW

**Review by Graywing13 — APPROVED** [review]
lgtm

**Comment by L0Lmaker** [comment]
There are some merge conflicts

**Review by Graywing13 — APPROVED** [review]
lgtm

**Review by L0Lmaker — APPROVED** [review]
LGTM

**Pull request merged**
