### PR TITLE
make globe spin

### LINKED ISSUE #165: Make Globe Spin on Load
Should stop spinning when user selects a Trip

### PR DESCRIPTION
**Pull request by vee-16**
source: https://docs.mapbox.com/mapbox-gl-js/example/globe-spin/

### CODE REVIEW

**Comment by L0Lmaker** [comment]
I love it 😍

**Comment by L0Lmaker** [comment]
One small issue is when the map is zoomed in it becomes fixed. Gonna look into it for a bit to see if we can get it to move while zoomed in.

**Comment by vee-16** [comment]
> One small issue is when the map is zoomed in it becomes fixed. Gonna look into it for a bit to see if we can get it to move while zoomed in.

I'll take a look so it seems to be locked in compact mode toggle, I will double check if this is consistent in main

(Edit: issue is currently in main, so unrelated to the changes of this PR. Good catch, we can add a commit to fix it here)

**Comment by L0Lmaker** [comment]
If its a problem on main then I think we are good for merge on this if no one else has any comments. @NLmeng @Graywing13 @AndyLiang1

**Comment by L0Lmaker** [comment]
Ooh I think you fixed it in this PR only 🤩

**Review by L0Lmaker — APPROVED** [review]
LGTM

**Pull request merged**
